In this project we learn how to use genetics algorithm to find a suitable solution for our problem.
In this project we have 6 gates and we need to predict the gates that would give us the desired outcome according to their inputs.
To get the desired results, first we make a population. Then, a part of our population produces children based on different probabilities achieved by giving fitter parts of population more chance to reproduce. 

PHASE 1

In this phase we define our chromosomes and the genes.
We define each chromosome as a set of gates in which each gene is a gate.

According to the defined problem we have 10 inputs, hence we need 9 gates, but it should be changed according to the input file.

In [4648]:
import numpy as np
import csv
import pandas as pd
from numpy import random
dif_bet_input_and_gates = 1
num_of_output = 1

In [4649]:
truth_table = pd.read_csv('truth_table.csv').to_numpy()

In [4650]:
truth_table

array([[False, False, False, ..., False, False,  True],
       [False, False, False, ..., False,  True, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [ True,  True,  True, ..., False,  True, False],
       [ True,  True,  True, ...,  True, False,  True],
       [ True,  True,  True, ...,  True,  True, False]])

In [4651]:
num_of_genes= truth_table.shape[1] - dif_bet_input_and_gates - num_of_output
num_of_inputs=truth_table.shape[1] - num_of_output

In [4652]:
num_of_genes

9

In [4653]:
num_of_inputs

10

In [4654]:
gates = ['and','or','xor','nand','nor','xnor']

PHASE 2

In this phase we need to produce our population. We can set the size of the population ourselves. The speed of getting our desired results may be different for different population sizes.
We set our population twice the number of our genes.

In [4655]:
population_scale_to_genes=2
num_of_chromosomes = population_scale_to_genes * num_of_genes

In this part we create the first population without any particular directions. We pick give each one of our 6 gates a number and we pick the genes randomly.

In [4656]:
population = random.randint(6, size=(num_of_chromosomes, num_of_genes))


In [4657]:
population

array([[5, 2, 4, 3, 4, 4, 4, 2, 1],
       [0, 0, 0, 3, 0, 3, 5, 0, 2],
       [2, 1, 0, 1, 3, 0, 2, 1, 5],
       [2, 3, 0, 1, 5, 3, 4, 4, 1],
       [4, 0, 4, 2, 5, 5, 2, 2, 1],
       [1, 2, 3, 1, 3, 5, 0, 4, 4],
       [1, 4, 3, 5, 4, 2, 3, 2, 2],
       [5, 4, 2, 3, 5, 4, 5, 1, 5],
       [1, 5, 0, 1, 4, 3, 2, 1, 4],
       [1, 4, 5, 0, 3, 0, 1, 5, 4],
       [5, 2, 4, 2, 5, 4, 1, 2, 3],
       [5, 5, 2, 0, 5, 1, 2, 0, 2],
       [5, 0, 1, 0, 5, 5, 4, 4, 2],
       [4, 4, 4, 3, 1, 4, 4, 0, 1],
       [0, 3, 5, 4, 3, 5, 2, 0, 5],
       [1, 3, 4, 5, 5, 3, 2, 5, 1],
       [3, 2, 5, 1, 0, 5, 2, 1, 4],
       [2, 2, 1, 0, 1, 0, 3, 2, 3]])

each number represents a gate.

In [4658]:
original_pop=population

PHASE 3 

In this phase we need to define a fitness function. 
We define better chromosomes as the ones that produce more number of right answers compared to the original answers from our truth tables.

In [4659]:
def gate(a, b, str_function):
    if str_function=='and':
        return (a and b)
    if str_function=='or':
        return (a or b)
    if str_function=='xor':
        return (a and not b) or (not a and b)
    if str_function=='nand':
        return not (a and b)
    if str_function=='nor':
        return not(a or b)
    if str_function=='xnor':
        return not((a and not b) or (not a and b))
    else:
        print('erroneous gene in chromosome')

In [4660]:
def cal_single_output(inputs ,chromosome):
    output_for_single = inputs[0]
    for gene in range(chromosome.shape[0]):
        output_for_single = gate(output_for_single,inputs[gene+1],gates[chromosome[gene]])
    return output_for_single


In [4661]:
def cal_all_outputs(truth_table_without_output, chromosome):
    outputs_for_chromosome=np.array([])
    for row in truth_table_without_output:
        outputs_for_chromosome = np.append(outputs_for_chromosome,cal_single_output(row,chromosome))
    return outputs_for_chromosome


In [4662]:
def fitness_function(population,truth_table):
    num_of_right_outputs_for_each_chromosome = np.array([])
    original_outputs=truth_table[:,num_of_inputs]
    #print('original_outputs',original_outputs)
    #print('population',population)
    for chromosome in population:
        output_for_chromosome = cal_all_outputs(truth_table[:,0:num_of_inputs], chromosome)
        right_outputs_for_this_chromosome=(output_for_chromosome==original_outputs).sum()
        num_of_right_outputs_for_each_chromosome = np.append(num_of_right_outputs_for_each_chromosome,right_outputs_for_this_chromosome)
    return num_of_right_outputs_for_each_chromosome

In [4663]:
fitness_of_population = fitness_function(population,truth_table)

In [4664]:
print(fitness_of_population)

[296. 354. 428. 320. 236. 632. 672. 364. 760. 720. 512. 278. 480. 133.
 726. 224. 840. 512.]


PHASE 4

In this phase we first choose parents to have children based on the fitness function. members of the population that have better fitness are more probable to be chosen as parents. First in each generation, we need to shuffle our population.


In [4665]:
np.random.shuffle(population)

The we calculate the fittness for this population:

In [4666]:
fitness_of_population = fitness_function(population,truth_table)

for selecting mates we use rulette wheel technique. 
For now we choose half of the population as parents but this can be changed. 

In [4667]:
parents_scale_in_each_step=2

In [4668]:
num_of_parents=int(num_of_chromosomes/parents_scale_in_each_step)

In [4669]:
num_of_parents

9

In [4670]:
population

array([[2, 1, 0, 1, 3, 0, 2, 1, 5],
       [3, 2, 5, 1, 0, 5, 2, 1, 4],
       [2, 3, 0, 1, 5, 3, 4, 4, 1],
       [5, 2, 4, 2, 5, 4, 1, 2, 3],
       [5, 0, 1, 0, 5, 5, 4, 4, 2],
       [4, 4, 4, 3, 1, 4, 4, 0, 1],
       [0, 3, 5, 4, 3, 5, 2, 0, 5],
       [5, 5, 2, 0, 5, 1, 2, 0, 2],
       [0, 0, 0, 3, 0, 3, 5, 0, 2],
       [1, 4, 5, 0, 3, 0, 1, 5, 4],
       [1, 3, 4, 5, 5, 3, 2, 5, 1],
       [1, 4, 3, 5, 4, 2, 3, 2, 2],
       [4, 0, 4, 2, 5, 5, 2, 2, 1],
       [1, 2, 3, 1, 3, 5, 0, 4, 4],
       [2, 2, 1, 0, 1, 0, 3, 2, 3],
       [5, 2, 4, 3, 4, 4, 4, 2, 1],
       [1, 5, 0, 1, 4, 3, 2, 1, 4],
       [5, 4, 2, 3, 5, 4, 5, 1, 5]])

In [4671]:
fitness_of_population = fitness_function(population,truth_table)

In [4672]:
fitness_of_population

array([428., 840., 320., 512., 480., 133., 726., 278., 354., 720., 224.,
       672., 236., 632., 512., 296., 760., 364.])

In [4673]:
def index_weighted_random_choice(fitness):
    max=fitness.sum()
    random_number=random.randint(0,max)
    sum=0
    for f in range(fitness.shape[0]):
        sum+=fitness[f]
        if sum>random_number:
            fitness[f]=0  #already chosen so should not be chosen again
            return f



In [4674]:
def new_population(fitness_of_population,population,num_of_parents):
    new_mates=np.zeros(num_of_parents)
    chosen_indexes=np.array([])
    chosen_index = index_weighted_random_choice(fitness_of_population)
    chosen_indexes=np.append(chosen_indexes,chosen_index)
    new_mates=np.array([population[chosen_index]])
    for i in range(num_of_parents-1):
        chosen_index = index_weighted_random_choice(fitness_of_population)
        chosen_indexes=np.append(chosen_indexes,chosen_index)
        new_mates=np.append(new_mates,[population[chosen_index]],0)
    population=np.delete(population,chosen_indexes,0) # without chosen mates
    return population, new_mates

In [4675]:
population, new_mates = new_population(fitness_of_population,population,num_of_parents)

now we have two arrays population will stay the same and the new mates will have childern which will be then added to the population


In [4676]:
population

array([[2, 1, 0, 1, 3, 0, 2, 1, 5],
       [2, 3, 0, 1, 5, 3, 4, 4, 1],
       [4, 4, 4, 3, 1, 4, 4, 0, 1],
       [0, 0, 0, 3, 0, 3, 5, 0, 2],
       [1, 3, 4, 5, 5, 3, 2, 5, 1],
       [4, 0, 4, 2, 5, 5, 2, 2, 1],
       [2, 2, 1, 0, 1, 0, 3, 2, 3],
       [5, 2, 4, 3, 4, 4, 4, 2, 1],
       [5, 4, 2, 3, 5, 4, 5, 1, 5]])

In [4677]:
new_mates

array([[1, 4, 5, 0, 3, 0, 1, 5, 4],
       [5, 5, 2, 0, 5, 1, 2, 0, 2],
       [0, 3, 5, 4, 3, 5, 2, 0, 5],
       [5, 2, 4, 2, 5, 4, 1, 2, 3],
       [1, 2, 3, 1, 3, 5, 0, 4, 4],
       [5, 0, 1, 0, 5, 5, 4, 4, 2],
       [1, 5, 0, 1, 4, 3, 2, 1, 4],
       [1, 4, 3, 5, 4, 2, 3, 2, 2],
       [3, 2, 5, 1, 0, 5, 2, 1, 4]])

Having our mates we produce the children using different crossovers.
In each crossover consecutive mates produce childern.

In uniform crossover we assign head to the first childern and flip a coin on choosing one of the parents to copy.

In [4678]:
def two_children_from_two_parents(mate_1,mate_2):
    first_child=[]
    second_child=[]
    for i in range(mate_1.shape[0]):
        coin=random.randint(2)
        if coin:
            first_child=np.append(first_child,mate_1[i])
            second_child=np.append(second_child,mate_2[i])
        else:
            first_child=np.append(first_child,mate_2[i])
            second_child=np.append(second_child,mate_1[i])
    return first_child,second_child



In [4679]:
def uniform_crossover(mates):
    for i in range(0,mates.shape[0]-1,2):
        mates[i],mates[i+1] = two_children_from_two_parents(mates[i],mates[i+1])
    return mates

    



In [4680]:
children = uniform_crossover(new_mates)

In [4681]:
children

array([[5, 4, 5, 0, 5, 0, 2, 5, 2],
       [1, 5, 2, 0, 3, 1, 1, 0, 4],
       [5, 2, 5, 4, 5, 5, 1, 0, 5],
       [0, 3, 4, 2, 3, 4, 2, 2, 3],
       [1, 2, 3, 1, 5, 5, 0, 4, 4],
       [5, 0, 1, 0, 3, 5, 4, 4, 2],
       [1, 4, 0, 5, 4, 3, 2, 2, 4],
       [1, 5, 3, 1, 4, 2, 3, 1, 2],
       [3, 2, 5, 1, 0, 5, 2, 1, 4]])

Now that we have our crossover, we need to have mutation for each gene individually with a probability which we set.

In [4682]:
prob_of_mutation=0.01

In [4683]:
def mutation(children):
    for i in range(children.shape[0]):
        for j in range(children.shape[0]):
            prob=random.randint(100)/100
            if prob<prob_of_mutation:
                children[i][j]=random.randint(6)
    return children

In [4684]:
mutated_children = mutation(children)

In [4685]:
mutated_children

array([[5, 4, 5, 0, 5, 0, 2, 5, 2],
       [1, 5, 2, 0, 3, 1, 1, 0, 4],
       [5, 2, 5, 4, 5, 5, 1, 0, 5],
       [0, 3, 4, 2, 3, 4, 2, 2, 3],
       [1, 2, 3, 1, 5, 5, 0, 4, 4],
       [5, 0, 1, 0, 3, 5, 4, 4, 2],
       [1, 4, 0, 5, 4, 3, 2, 2, 4],
       [1, 5, 3, 1, 4, 2, 3, 1, 2],
       [3, 2, 5, 1, 0, 5, 2, 1, 4]])

Now that we have our children, we need to make our new population using a part of old population and new children.

In [4686]:
population=np.append(population,mutated_children,0)

In [4687]:
population

array([[2, 1, 0, 1, 3, 0, 2, 1, 5],
       [2, 3, 0, 1, 5, 3, 4, 4, 1],
       [4, 4, 4, 3, 1, 4, 4, 0, 1],
       [0, 0, 0, 3, 0, 3, 5, 0, 2],
       [1, 3, 4, 5, 5, 3, 2, 5, 1],
       [4, 0, 4, 2, 5, 5, 2, 2, 1],
       [2, 2, 1, 0, 1, 0, 3, 2, 3],
       [5, 2, 4, 3, 4, 4, 4, 2, 1],
       [5, 4, 2, 3, 5, 4, 5, 1, 5],
       [5, 4, 5, 0, 5, 0, 2, 5, 2],
       [1, 5, 2, 0, 3, 1, 1, 0, 4],
       [5, 2, 5, 4, 5, 5, 1, 0, 5],
       [0, 3, 4, 2, 3, 4, 2, 2, 3],
       [1, 2, 3, 1, 5, 5, 0, 4, 4],
       [5, 0, 1, 0, 3, 5, 4, 4, 2],
       [1, 4, 0, 5, 4, 3, 2, 2, 4],
       [1, 5, 3, 1, 4, 2, 3, 1, 2],
       [3, 2, 5, 1, 0, 5, 2, 1, 4]])

we can now produce our new fittness

In [4688]:
fitness_function(population,truth_table)

array([428., 320., 133., 354., 224., 236., 512., 296., 364., 544., 856.,
       608., 512., 672., 480., 672., 760., 840.])

Because we have only had one generation, we can not see promising results.

In [4689]:
num_of_generations=5

In [4690]:
def all_generation(num_of_generations,population,truth_table):
    max_of_each_iteration=[]
    for i in range(num_of_generations):
        np.random.shuffle(population)
        fitness_of_population = fitness_function(population,truth_table)
        population, new_mates = new_population(fitness_of_population,population,num_of_parents)
        children = uniform_crossover(new_mates)
        mutated_children = mutation(children)
        population=np.append(population,mutated_children,0)
        current_max=max(fitness_function(population,truth_table))
        max_of_each_iteration=np.append(max_of_each_iteration,current_max)
    return max_of_each_iteration


In [4691]:
all_generation(num_of_generations,population,truth_table)


array([856., 892., 868., 868., 880.])

We can see that after 5 generations the outcome has improved inconsistently. We continue:

In [4692]:
num_of_generations=5
all_generation(num_of_generations,population,truth_table)

array([840., 832., 772., 868., 940.])

In [4693]:
num_of_generations=50
all_generation(num_of_generations,population,truth_table)

array([848., 856., 828., 824., 808., 928., 928., 850., 864., 816., 784.,
       864., 864., 864., 864., 864., 904., 904., 896., 896., 896., 872.,
       872., 848., 816., 832., 876., 832., 864., 810., 868., 868., 868.,
       800., 800., 856., 878., 894., 760., 784., 864., 888., 872., 888.,
       824., 864., 842., 872., 896., 896.])

By continuing we can see more consistency.

PHASE 5 

Q1.  I chose my fitness function the number of the correct answers produced by our getes. This is because the more correct answers it produces, the more gates we've probably got right. 

Q2. Uniform crossover has been used to increase the chance of producing different combinations of gates. 

Q3. since we have used uniform crossover, we have used 0.5 probability, but we have the prob_of_mutation used for mutation. We know that this probabilty helps when we reach a particular outcome. The higher it is the faster we can come out of consistent outcomes.
We can change this probability to see how it effects our results.

In [4694]:
prob_of_mutation=0.1
population=original_pop
num_of_generations=10
all_generation(num_of_generations,population,truth_table)

array([848., 848., 848., 872., 872., 832., 820., 752., 736., 728.])

we can see that overall increasing this probability helps with the results but since the original population is chosen randomly, we can not say for sure. Hence we try this with a stable begining population.

In [4695]:
population = np.zeros([num_of_chromosomes, num_of_genes])
prob_of_mutation=0.01
population=original_pop
num_of_generations=10
all_generation(num_of_generations,population,truth_table)

array([848., 796., 704., 896., 864., 976., 960., 880., 944., 754.])

In [4696]:
population = np.zeros([num_of_chromosomes, num_of_genes])
prob_of_mutation=0.1
population=original_pop
num_of_generations=10
all_generation(num_of_generations,population,truth_table)

array([892., 892., 896., 896., 888., 880., 864., 832., 876., 876.])

we can see that having more generations, higher mutation probality helps to have bette results.

Q4. This is because we are stuck at a local minimum and the uniform crossover does not produce new children that are different from their parents. We can solve this problem by choosing a higher probability for mutation. This mutation helps produce children that are different from their parents. 
We can see how it effects our results in Q3.

In [4697]:
population = np.zeros([num_of_chromosomes, num_of_genes])
prob_of_mutation=0.1
population=original_pop
num_of_generations=100
all_generation(num_of_generations,population,truth_table)

array([860., 860., 784., 828., 808., 808., 784., 648., 736., 736., 736.,
       672., 964., 848., 848., 848., 848., 768., 768., 800., 755., 800.,
       800., 800., 800., 736., 800., 792., 864., 800., 840., 760., 784.,
       864., 800., 912., 944., 792., 760., 836., 836., 848., 892., 892.,
       800., 736., 704., 792., 752., 752., 762., 795., 860., 860., 678.,
       736., 768., 832., 832., 832., 754., 800., 800., 960., 912., 776.,
       694., 800., 800., 800., 800., 832., 792., 782., 832., 840., 816.,
       880., 880., 904., 904., 832., 908., 880., 896., 832., 832., 920.,
       920., 896., 864., 896., 896., 896., 896., 864., 864., 864., 918.,
       918.])

we can also see that more generation helps with better results.